name: Push to GHCR

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: docker login
        run: echo $GH_TOKEN | docker login ghcr.io -u viranch --password-stdin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: docker build
        run: docker build -t ghcr.io/viranch/transmission .

      - name: docker push
        run: docker push ghcr.io/viranch/transmission
